accounts/urls.py
from django.urls import path, include
from . import views

app_name = 'accounts'
urlpatterns = [
    # include all default authentication url
    path("", include('django.contrib.auth.urls')),
    # include registration urls
    path('registration', views.register, name='register'),

]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    # making home page
    path('', views.home, name='home'),
    path('blogs/', views.blogs, name='blogs'),
    path('posts/<int:post_id>/', views.posts, name='posts'),
    path('Add blog/', views.new_blog, name='new_blog'),
    path('Add post/<int:blog_id>/', views.new_post, name='new_post'),
    path('Edit post/<int:posts_id>/', views.edit_post, name='edit_post'),
]

blogs/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('blog.urls')),
]

accounts/models.py
from django.db import models

# Create your models here.

blog/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Blogs(models.Model):
    """create model for blogs"""
    blog = models.CharField(max_length=200)
    publish = models.DateTimeField(auto_now=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = 'Blogs'

    def __str__(self):
        return self.blog


class Posts(models.Model):
    """create model for Posts"""
    post = models.ForeignKey(Blogs, on_delete=models.CASCADE)
    text = models.TextField()
    publish = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'Posts'

    def __str__(self):
        return self.text

blog/forms.py
from django import forms
from .models import Blogs, Posts

class BlogsForm(forms.ModelForm):
    """create blog form"""
    class Meta:
        model = Blogs
        fields = ['blog']
        labels = {'blog': ''}

class PostsForm(forms.ModelForm):
    """create post form"""
    class Meta:
        model = Posts
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

# Create your views here.
def register(request):
    """Make register function for registration"""
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(request.POST)
        if form.is_valid():
            new_user = form.save()
            login(request, new_user)
            return redirect('blog:home')

    context = {'form': form}
    return render(request, 'registration/register.html', context)

blog/views.py
from django.shortcuts import render, redirect
from .models import Blogs, Posts
from .forms import BlogsForm, PostsForm
from django.contrib.auth.decorators import login_required
from django.http import Http404

# Create your views here.
def home(request):
    """creat view funcitions for home page."""
    posts = Posts.objects.order_by('-publish')

    context = {'posts': posts}
    return render(request, 'blog/Home.html', context)


@login_required()
def blogs(request):
    """Create view functoins for blogs"""
    blogs = Blogs.objects.filter(owner=request.user).order_by('-publish')

    context = {'blogs': blogs}
    return render(request, 'blog/blogs.html', context)


@login_required()
def posts(request, post_id):
    """Create view functoins for blogs"""
    blogs = Blogs.objects.get(id=post_id)
    posts = blogs.posts_set.order_by('-publish')
    check_blog_owner(request, blogs)

    context = {'blogs': blogs, 'posts': posts}
    return render(request, 'blog/posts.html', context)


@login_required()
def new_blog(request):
    """Create view functions for new_blog"""
    if request.method != 'POST':
        form = BlogsForm()
    else:
        form = BlogsForm(request.POST)
        if form.is_valid():
            new_blogs = form.save(commit=False)
            new_blogs.owner = request.user
            new_blogs.save()
            return redirect('blog:blogs')

    context = {'form': form}
    return render(request, 'blog/new_blog.html', context)


@login_required()
def new_post(request, blog_id):
    """Create view functions for new_blog"""
    blog = Blogs.objects.get(id=blog_id)
    check_blog_owner(request, blog)

    if request.method != 'POST':
        form = PostsForm()
    else:
        form = PostsForm(data=request.POST)
        if form.is_valid():
            postss = form.save(commit=False)
            postss.post = blog
            postss.save()
            return redirect('blog:posts', post_id=blog.id)

    context = {'form': form, 'blog': blog}
    return render(request, 'blog/new_post.html', context)


@login_required()
def edit_post(request, posts_id):
    """create function for edit post"""
    posts = Posts.objects.get(id=posts_id)
    blog = posts.post
    check_blog_owner(request, blog)
    if request.method != 'POST':
        form = PostsForm(instance=posts)
    else:
        form = PostsForm(instance=posts, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('blog:posts', post_id=blog.id)

    context = {'post': posts, 'blog': blog, 'form': form}
    return render(request, 'blog/edit_post.html', context)

def check_blog_owner(request, blog):
    """check user status"""
    if blog.owner != request.user:
        raise Http404

blog/templates/blog/Home.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Home page</title>
</head>
<body>
</body>
</html>

{% extends 'blog/base.html' %}
{% load django_bootstrap5 %}
{% block page_header %}

<h1 class="display-4"> Posts </h1>
<ul>
  {% for post in posts %}


  <div class="card mb-2">
    <h4 class="card-header">
    {{post.publish|date:"M d, Y H:i"}}

    </h4>

    <div class="card-body">
      {{post.text}}

    </div>
      <div class=" ms-auto ">
        <small class="card-footer ">Posted by {{post.post.owner}}</small>
      </div>
        <h4 class="card-footer ">
      {% if user.is_authenticated %}

      {% else %}
      <a href="{% url 'accounts:login'%}">Log in &raquo;</a>
      {% endif %}
    </h4>
  </div>


  {% endfor %}

</ul>
{% endblock page_header %}

blog/templates/blog/base.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name ='viewport' content="width = device-width, initial-scale=1"> 
  <title>Blogs</title>
  {% load django_bootstrap5 %}
  {% bootstrap_css %}
  {% bootstrap_javascript %}
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'blog:home' %}">Home</a>
        <a class="nav-link" href="{% url 'blog:blogs' %}">Blogs</a></li>


        <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarCollapse" aria-controls="navbarCollapse"
                aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
             <ul class="navbar-nav me-auto mb-2 mb-md-0">
             </ul>
<!--                  Accounts related links-->
              <ul class="navbar-nav ms-auto mb-2 mb-md-0">
                {% if user.is_authenticated %}
                <li class="nav-item">
                <span class="navbar-text me-2">Hello, {{user.username}}.
                </span></li>
                {% else %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'accounts:register' %}">Register</a></li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'accounts:login' %}">Log in</a></li>
                {% endif %}
              </ul> <!-- end of accounts related link -->

                {% if user.is_authenticated %}
                <form action="{% url 'accounts:logout' %}" method="post">
                  {% csrf_token %}
                  <button name="submit" class="btn btn-outline-secondary btn-sm">Log out</button>
                </form>
                {% endif %}
        </div>
      </div>
    </nav>
    <main>
      <div class="container bp-2 mb-2">
        {% block page_header %}{% endblock page_header%}
      </div>
      <div>
        {% block content %}{% endblock content %}
      </div>
    </main>
</body>
</html>

blog/templates/blog/blogs.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Blogs</title>
</head>
<body>

</body>
</html>
{% extends 'blog/base.html' %}
{% load django_bootstrap5 %}

{% block page_header %}

<h1 class="display-3">Blogs</h1>
<h2 class="display-9"><a href="{% url 'blog:new_blog' %}">Add new blog</a></h2>

{% endblock page_header %}

{% block content %}

<ul class="list-group border-bottom bp-2 mb-4">
    {% for blog in blogs %}
    <li class="list-group-item border-0">
        <a href="{% url 'blog:posts' blog.id %}">{{blog}}</a>
    </li>
    {% endfor %}
</ul>

{% endblock content %}

blog/templates/blog/edit_post.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Edit post</title>
</head>
<body>

</body>
</html>
{% extends 'blog/base.html' %}
{% load django_bootstrap5 %}

{% block page_header %}

<h1 class="display-3"> Edit post: <a href="{% url 'blog:posts' blog.id %}"><small>{{blog}}</small></a>
</h1>
{% endblock page_header %}

{% block content %}

<form action="{% url 'blog:edit_post' post.id %}" method="post">
  {% csrf_token %}
  {% bootstrap_form form %}
  {% bootstrap_button type='submit' content='Edit Post' %}

</form>

{% endblock content %}

blog/templates/blog/new_blog.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>New blog</title>
</head>
<body>

</body>
</html>
{% extends 'blog/base.html' %}
{% load django_bootstrap5 %}

{% block page_header %}

<h1 class="display-3"> Add New blog</h1>
{% endblock page_header %}

{% block content%}


<form action="{% url 'blog:new_blog' %}" method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% bootstrap_button type="submit" content="Add Blog" %}

</form>

{% endblock content%}

blog/templates/blog/new_post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add Post</title>
</head>
<body>

</body>
</html>
{% extends 'blog/base.html' %}
{% load django_bootstrap5 %}

{% block page_header %}

<h1 class="display-3"> Add New Post</h1>
<h2 class="display-9"><a href="{% url 'blog:posts' blog.id%}">{{blog}}</a></h2>

{% endblock page_header %}

{% block content %}
    <form action="{% url 'blog:new_post' blog.id %}" method="post" >
        {% csrf_token %}
        {% bootstrap_form form %}
        {% bootstrap_button type='submit' content='Add Post' %}
    </form>

{% endblock content %}

blog/templates/blog/posts.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Posts</title>
</head>
<body>

</body>
</html>
{% extends 'blog/base.html' %}
{% load django_bootstrap5 %}

{% block page_header %}
<h1 class="display-3">Posts: <a href="{% url 'blog:blogs'%}">{{blogs}}</a></h1>
<h2 class="display-5"><a href="{% url 'blog:new_post' blogs.id%}">Add new post</a></h2>

{% endblock page_header %}

{% block content %}

<ul>
  {% for post in posts %}
  <div class="card mb-2">
    <h4 class="card-header">
        {{post.publish|date:'M d, Y H:i'}}

    </h4>
    <div class="card-body border rounded-3">
        {{post}}
    </div>
      <h7 class="card-footer ms-auto">
          <a href="{% url 'blog:edit_post' post.id %}">Edit Post</a>
      </h7>
  </div>
  {% endfor %}
</ul>

{% endblock content %}